# Generated by Django 5.1.3 on 2024-12-05 17:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invitation_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
