# Generated by Django 5.1.3 on 2024-12-04 19:46

import uuid
from django.db import migrations

def gen_uuid(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    for user in CustomUser.objects.all():
        user.invitation_code = uuid.uuid4()
        user.save(update_fields=['invitation_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_invitation_code'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
