# Generated by Django 5.1.3 on 2024-12-04 19:46

import uuid
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20241205_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="invitation_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
