# Generated by Django 5.1.3 on 2024-12-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20241205_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='invitation_code',
        ),
    ]
