# Generated by Django 5.1.3 on 2024-12-05 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20241205_2215'),
        ('users', '0006_remove_customuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='teams.team'),
        ),
    ]
