# Generated by Django 5.1.3 on 2024-12-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0002_remove_taskevaluation_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskevaluation',
            name='criteria',
        ),
        migrations.AddField(
            model_name='taskevaluation',
            name='completeness',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskevaluation',
            name='quality',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskevaluation',
            name='timeliness',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
