# Generated by Django 5.1.3 on 2024-12-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_schedulerevent_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerevent',
            name='event_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schedulerevent',
            name='event_type',
            field=models.CharField(choices=[('task', 'Task'), ('meeting', 'Meeting')], max_length=50),
        ),
    ]
